- icon: "icon ion-social-reddit-outline"
  title: "Artificial Intelligence"
  content: "How your company can benefit from the latest discoveries in Artificial Intelligence."

- icon: "icon ion-podium"
  title: "Data Architecture"
  content: "Treat your data as a business asset and apply data management best practices."

- icon: "icon ion-image"
  title: "Business Architecture"
  content: "How business functions can be modeled to become a solid foundation for effective strategy execution."

- icon: "icon ion-network"
  title: "Solutions Architecture"
  content: "Build evolvable future-proof solutions that solve business problems."
